# permissions for end users to edit submariners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submariner-editor-role
rules:
- apiGroups:
  - submariner.io
  resources:
  - submariners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - submariner.io
  resources:
  - submariners/status
  verbs:
  - get
