# permissions for end users to view submariners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: submariner-viewer-role
rules:
- apiGroups:
  - submariner.io
  resources:
  - submariners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - submariner.io
  resources:
  - submariners/status
  verbs:
  - get
