
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: submariner-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - rbac
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - update
- apiGroups:
  - rbac
  resources:
  - clusterroles
  verbs:
  - create
  - get
  - update
- apiGroups:
  - rbac
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - update
- apiGroups:
  - rbac
  resources:
  - roles
  verbs:
  - create
  - get
  - update
- apiGroups:
  - submariner.io
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - submariner.io
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - submariner.io
  resources:
  - gateways
  verbs:
  - list
- apiGroups:
  - submariner.io
  resources:
  - gateways
  - submariners
  verbs:
  - list
  - watch
- apiGroups:
  - submariner.io
  resources:
  - servicediscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - submariner.io
  resources:
  - servicediscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - submariner.io
  resources:
  - submariners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - submariner.io
  resources:
  - submariners/status
  verbs:
  - get
  - patch
  - update
