## Append samples you want in your CSV to this file as resources ##
resources:
- submariner.io_v1alpha1_submariner.yaml
- submariner.io_v1alpha1_broker.yaml
- submariner.io_v1alpha1_servicediscovery.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
