apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: broker-sample
spec:
#  defaultCustomDomains:
#  globalnetCidrRange:
  defaultGlobalnetClusterSize: 8192
  globalnetEnabled: false
  serviceDiscovery: true
