---
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v**'

name: Upgrade tests
jobs:
  upgrade-e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        globalnet: ['', 'globalnet']
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Install an old cluster, upgrade it and check it
        run: |
          make upgrade-e2e using="${{ matrix.globalnet }}"

      - name: Post Mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
